package org.polaric.colorful;

/**
 * Created by WngShhng on 2018/6/1. */
public interface PermissionRequestCode {
    int REQUEST_PERMISSION_STORAGE = 0x2001;
    int REQUEST_PERMISSION_PHONE_STATE = 0x2002;
    int REQUEST_PERMISSION_LOCATION = 0x2003;
    int REQUEST_PERMISSION_MICROPHONE = 0x2004;
    int REQUEST_PERMISSION_SMS = 0x2005;
    int REQUEST_PERMISSION_SENSORS = 0x2006;
    int REQUEST_PERMISSION_CONTACTS = 0x2007;
    int REQUEST_PERMISSION_CAMERA = 0x2008;
    int REQUEST_PERMISSION_CALENDAR = 0x2009;
}
